<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="Snail.Toolkit.Authentication.JwtBearer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Client\Client.csproj" />
    <ProjectReference Include="..\..\src\Server\Server.csproj" />
  </ItemGroup>

</Project>
