<Project>

  <Import Project="..\Directory.Build.props" />

  <PropertyGroup>
    <PackageTags>signalr;reactive;streaming;chunking;transfer</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)..\README.md" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>

</Project>
